"""Export addons from Stremio local storage."""
import json
import sys
from pathlib import Path


def get_stremio_storage_path() -> Path | None:
    """Find the Stremio storage file based on OS."""
    home = Path.home()

    paths = [
        home / ".config" / "Stremio" / "UserData" / "storage.json",
        home / ".stremio" / "storage.json",
        home / "AppData" / "Roaming" / "Stremio" / "UserData" / "storage.json",
        home / "Library" / "Application Support" / "Stremio" / "UserData" / "storage.json",
    ]

    for path in paths:
        if path.exists():
            return path

    return None


def get_chrome_local_storage_path() -> Path | None:
    """Find Chrome local storage for stremio.com."""
    home = Path.home()

    wsl_windows_path = "/mnt/c/Users/strubloid/AppData/Local/Google/Chrome/User Data/Default"

    if Path(wsl_windows_path).exists():
        local_storage = Path(wsl_windows_path) / "Local Storage" / "leveldb"
        if local_storage.exists():
            return local_storage

    return None


def extract_addon_urls(storage_path: Path) -> list[str]:
    """Extract addon URLs from Stremio storage file."""
    with open(storage_path, "r", encoding="utf-8") as f:
        storage = json.load(f)

    addons = storage.get("addons", [])
    urls = []

    for addon in addons:
        transport_url = addon.get("transportUrl")
        if transport_url:
            clean_url = transport_url.rstrip("/").replace("/manifest.json", "")
            urls.append(clean_url)

    return urls


def export_addons_to_file(output_path: Path | None = None) -> int:
    """Export addons from Stremio storage to addons.txt."""
    storage_path = get_stremio_storage_path()

    if not storage_path:
        print("Stremio Desktop storage not found. Checking Stremio Web...")
        print("")
        print("For Stremio Web, please manually export your addons:")
        print("")
        print("1. Open https://stremio.com in your browser")
        print("2. Open Developer Tools (F12)")
        print("3. Go to Application → Local Storage → stremio.com")
        print("4. Look for 'addons' key and copy the URLs")
        print("")
        print("Or use one of these community addon lists:")
        print("  - https://raw.githubusercontent.com/Stremio/stremio-official-addons/master/index.json")
        print("")
        print("You can manually create addons.txt with URLs like:")
        print("  https://torrentio.strem.fun/")
        print("  https://mediafusion.elfhosted.com/")
        print("  https://thepiratebay-plus.strem.fun/")
        print("")
        return 1

    urls = extract_addon_urls(storage_path)

    if not urls:
        print("Warning: No addons found in Stremio storage.")
        return 1

    if output_path is None:
        output_path = Path(__file__).resolve().parents[2] / "addons.txt"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Stremio Addon URLs - Exported from Stremio\n")
        f.write("# Auto-generated by py-stremio-export\n")
        f.write("\n")
        for url in urls:
            f.write(url + "\n")

    print(f"Exported {len(urls)} addons to {output_path}")
    return 0


def main():
    """CLI entry point for exporting addons."""
    output = None

    if len(sys.argv) > 1:
        output = Path(sys.argv[1])

    return export_addons_to_file(output)


if __name__ == "__main__":
    sys.exit(main())
