"""Addon URL configuration rules for host-specific runtime setup."""

from .addon_url_configurer import AddonUrlConfigurer
from .builtin_addons import (
    ADDON_REGISTRY,
    AddonDef,
    make_addon_class,
)
from .stremio import StremioAddonConfigurer
from .torrentio_family.TorrentioAddonConfigurer import TorrentioAddonConfigurer
from .comet_family.CometAddonConfigurer import CometAddonConfigurer
from .comet_family.HDHubAddonConfigurer import HDHubAddonConfigurer
from .comet_family.StremThruAddonConfigurer import StremThruAddonConfigurer
from .comet_family.BrazucaAddonConfigurer import BrazucaAddonConfigurer
from .comet_family.GuindexAddonConfigurer import GuindexAddonConfigurer
from .anime.NyaaAddonConfigurer import NyaaAddonConfigurer
from .anime.YomiAddonConfigurer import YomiAddonConfigurer
from .aggregators.IntellDebridSearchAddonConfigurer import IntellDebridSearchAddonConfigurer

# Re-export all explicit addon classes for convenience
from .builtin_addons import (
    # Torrentio
    TorrentioAddon,
    TorrentioSortSeedersAddon,
    TorrentioPortugueseAddon,
    TorrentioSpanishAddon,
    TorrentioHindiAddon,
    TorrentioLiteAddon,
    # Comet / HDHub / StremThru / Brazuca / Guindex
    CometAddon,
    CometElfHostedAddon,
    CometNetAddon,
    HDHubAddon,
    StremThruAddon,
    BrazucaTorrentsAddon,
    GuindexAddon,
    # Aggregators
    AIOStreamsAddon,
    CineTorrentAddon,
    CinescrapeAddon,
    DebridSearchAddon,
    EasyNewsPlusAddon,
    FlixStreamsAddon,
    JackettioAddon,
    KnightCrawlerAddon,
    KodAddon,
    MediaFusionAddon,
    MyCineAddon,
    NebulaStreamsAddon,
    NucleusAddon,
    OrionAddon,
    PeerflixAddon,
    StremifyAddon,
    StreamViXAddon,
    SupremeAddon,
    ThePirateBayPlusAddon,
    TillAddon,
    TorrinAddon,
    VidFastProAddon,
    YtztvioAddon,
    # Anime
    AnimeKitsuAddon,
    AkumaAddon,
    AnimepaheAddon,
    AnimeoAddon,
    OnePaceAddon,
    HanimeAddon,
    AnimesSeasonAddon,
    # IPTV
    AIOStreamingAddon,
    ArgentinaTVAddon,
    EireGBTVAddon,
    FreeMiumTVAddon,
    GreekTVAddon,
    SkyflixAddon,
    WatchioAddon,
    XtreamProAddon,
    # Regional
    DubbindoAddon,
    EinthusanAddon,
    FenixFlixAddon,
    FigaroCorsoAddon,
    FrenchioAddon,
    FTVStremioAddon,
    LatinMoviesAddon,
    MainelocalnewsAddon,
    MicoLeaoDubladoAddon,
    NoTorrentAddon,
    RicosStremioAddon,
    VStremioAddon,
    # Misc
    ConsumetAddon,
    FShareAddon,
    SuperFlixAddon,
    WatchHubAddon,
    YouTubeProAddon,
    # Debrid
    DMMAddon,
    PremiumizeAddon,
    PearioAddon,
)

__all__ = [
    # Configurers
    "AddonUrlConfigurer",
    "BrazucaAddonConfigurer",
    "CometAddonConfigurer",
    "GuindexAddonConfigurer",
    "HDHubAddonConfigurer",
    "IntellDebridSearchAddonConfigurer",
    "NyaaAddonConfigurer",
    "StremioAddonConfigurer",
    "StremThruAddonConfigurer",
    "TorrentioAddonConfigurer",
    "YomiAddonConfigurer",
    # Registry
    "ADDON_REGISTRY",
    "AddonDef",
    "make_addon_class",
    # All addon classes
    "TorrentioAddon",
    "TorrentioSortSeedersAddon",
    "TorrentioPortugueseAddon",
    "TorrentioSpanishAddon",
    "TorrentioHindiAddon",
    "TorrentioLiteAddon",
    "CometAddon",
    "CometElfHostedAddon",
    "CometNetAddon",
    "HDHubAddon",
    "StremThruAddon",
    "BrazucaTorrentsAddon",
    "GuindexAddon",
    "AIOStreamsAddon",
    "CineTorrentAddon",
    "CinescrapeAddon",
    "DebridSearchAddon",
    "EasyNewsPlusAddon",
    "FlixStreamsAddon",
    "JackettioAddon",
    "KnightCrawlerAddon",
    "KodAddon",
    "MediaFusionAddon",
    "MyCineAddon",
    "NebulaStreamsAddon",
    "NucleusAddon",
    "OrionAddon",
    "PeerflixAddon",
    "StremifyAddon",
    "StreamViXAddon",
    "SupremeAddon",
    "ThePirateBayPlusAddon",
    "TillAddon",
    "TorrinAddon",
    "VidFastProAddon",
    "YtztvioAddon",
    "AnimeKitsuAddon",
    "AkumaAddon",
    "AnimepaheAddon",
    "AnimeoAddon",
    "OnePaceAddon",
    "HanimeAddon",
    "AnimesSeasonAddon",
    "AIOStreamingAddon",
    "ArgentinaTVAddon",
    "EireGBTVAddon",
    "FreeMiumTVAddon",
    "GreekTVAddon",
    "SkyflixAddon",
    "WatchioAddon",
    "XtreamProAddon",
    "DubbindoAddon",
    "EinthusanAddon",
    "FenixFlixAddon",
    "FigaroCorsoAddon",
    "FrenchioAddon",
    "FTVStremioAddon",
    "LatinMoviesAddon",
    "MainelocalnewsAddon",
    "MicoLeaoDubladoAddon",
    "NoTorrentAddon",
    "RicosStremioAddon",
    "VStremioAddon",
    "ConsumetAddon",
    "FShareAddon",
    "SuperFlixAddon",
    "WatchHubAddon",
    "YouTubeProAddon",
    "DMMAddon",
    "PremiumizeAddon",
    "PearioAddon",
]