from py_stremio.components.addons.experimental import (
    generate_experimental_urls,
    load_experimental_urls,
)
from py_stremio.components.collect.sources import SourceResult
from py_stremio.components.collect.tester import TestResult as AddonTestResult


def test_load_experimental_urls_uses_addons_directory(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    path = tmp_path / "addons" / "experimental.txt"
    path.parent.mkdir()
    path.write_text("# generated\nhttps://one.example\nhttps://two.example # note\n")

    assert load_experimental_urls() == [
        "https://one.example",
        "https://two.example",
    ]


def test_generate_experimental_urls_writes_reachable_candidates(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        "py_stremio.components.collect.sources.run_all_sources",
        lambda verbose=True: SourceResult(
            name="all",
            urls={"https://two.example/", "https://one.example"},
        ),
    )
    monkeypatch.setattr(
        "py_stremio.components.collect.tester.test_urls",
        lambda urls, max_workers=8, verbose=True: AddonTestResult(
            working=[("https://two.example/", "Two")],
            dead=["https://one.example"],
            total_tested=2,
        ),
    )

    assert generate_experimental_urls(verbose=False) == ["https://two.example"]
    assert load_experimental_urls() == ["https://two.example"]
    assert "Generated by interactive menu option 7" in (
        tmp_path / "addons" / "experimental.txt"
    ).read_text()
