"""Experimental addon registry — last-resort addon URLs.

Experimental addons are only queried when all normal addons (built-in + addons/addons.txt)
fail to produce a working download for a given episode or movie.  This tier gives
the user a safety net for niche content, unstable addons, or geographic fallbacks
without polluting the primary search path.

File format (addons/experimental.txt):
  Same as addons/addons.txt: one URL per line, '#' for comments.
  Each URL is a clean manifest URL, exactly like the main file.

Usage:
    from py_stremio.components.addons.experimental import (
        load_experimental_urls,
        ExperimentalAddonManager,
    )

    urls = load_experimental_urls()
    manager = ExperimentalAddonManager(urls)
    streams, working = manager.search(type_, stremio_id)
"""

from __future__ import annotations

from typing import Any

from py_stremio.components.addons.base import UrlAddon
from py_stremio.components.addons.manager import SEARCH_CONCURRENCY
from py_stremio.components.addons.models import StreamInfo
from py_stremio.components.addons.paths import experimental_addons_path
from py_stremio.components.configs.app_settings import settings
from py_stremio.utils.atomic_write import atomic_write_text

EXPERIMENTAL_FILE = "addons/experimental.txt"


def load_experimental_urls() -> list[str]:
    """Load experimental addon URLs from addons/experimental.txt.

    Returns an empty list when the file does not exist or contains no
    uncommented lines.  URLs are returned in file order, stripped.
    """
    path = experimental_addons_path()

    if not path.exists():
        return []

    urls: list[str] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Strip inline comments
        cleaned = line.split("#")[0].strip()
        if cleaned:
            urls.append(cleaned)
    return urls


def generate_experimental_urls(*, max_workers: int = 8, verbose: bool = True) -> list[str]:
    """Discover reachable addon manifests and replace the experimental inventory."""
    from datetime import datetime

    from py_stremio.components.collect.sources import run_all_sources
    from py_stremio.components.collect.tester import test_urls
    from py_stremio.components.addons.factory import load_addon_urls

    collected = run_all_sources(verbose=verbose)
    tested = test_urls(sorted(collected.urls), max_workers=max_workers, verbose=verbose)
    normal_urls = {
        url.rstrip("/").removesuffix("/manifest.json")
        for url in load_addon_urls()
    }
    urls = sorted({
        url.rstrip("/")
        for url, _name in tested.working
        if url.rstrip("/").removesuffix("/manifest.json") not in normal_urls
    })
    header = [
        "# Generated experimental addon manifest URLs",
        f"# Last updated: {datetime.now().astimezone().isoformat(timespec='seconds')}",
        "# Generated by interactive menu option 7.",
        "# This file is local and ignored by git.",
        "",
    ]
    atomic_write_text(experimental_addons_path(), "\n".join([*header, *urls, ""]))
    return urls


class ExperimentalAddonManager:
    """Lightweight addon manager tailored for experimental URLs.

    Unlike the primary AddonManager, this one:
    - Only queries addon URLs from the experimental file
    - Always runs with best-effort semantics (no persistence)
    - Returns streams + working URLs, caller decides what to do
    """

    def __init__(self, urls: list[str] | None = None):
        self.addons: list[UrlAddon] = []
        self.api_key = settings.REAL_DEBRID_API_KEY

        if urls:
            for raw_url in urls:
                try:
                    addon = UrlAddon(raw_url)
                    addon.api_key = self.api_key
                    self.addons.append(addon)
                except Exception:
                    pass  # skip malformed URLs silently

    def search(
        self,
        type_: str,
        stremio_id: str,
    ) -> tuple[list[StreamInfo], list[str]]:
        """Search all experimental addons for *stremio_id*.

        Returns (streams, working_urls) where working_urls are the
        normalised URLs of addons that returned at least one stream.
        """
        from concurrent.futures import ThreadPoolExecutor, as_completed
        from py_stremio.components.configs.app_settings import settings

        if not self.addons:
            return [], []

        total = len(self.addons)
        all_streams: list[StreamInfo] = []
        working_urls: list[str] = []
        result_lock = threading_lock()

        executor = ThreadPoolExecutor(max_workers=min(SEARCH_CONCURRENCY, total))
        futures = {}
        try:
            futures = {
                executor.submit(self._try_addon, addon, type_, stremio_id): addon
                for addon in self.addons
            }
            for future in as_completed(futures):
                addon = futures[future]
                try:
                    streams = future.result(timeout=20)
                except Exception:
                    streams = []
                if streams:
                    with result_lock:
                        addon_url = self._addon_url(addon)
                        for s in streams:
                            s.addon_url = s.addon_url or addon_url
                        all_streams.extend(streams)
                        if addon_url and addon_url not in working_urls:
                            working_urls.append(addon_url)
        finally:
            executor.shutdown(wait=True)

        return all_streams, working_urls

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _try_addon(addon: UrlAddon, type_: str, id_: str) -> list[StreamInfo]:
        """Query one experimental addon URL."""
        from py_stremio.components.addons.addon_search_service import query_addon_for_streams

        try:
            url = addon.get_url(getattr(addon, "api_key", None))
        except TypeError:
            url = addon.get_url()

        if not url:
            return []
        return query_addon_for_streams(url, type_, id_)

    @staticmethod
    def _addon_url(addon: UrlAddon) -> str:
        """Return the clean persistence-safe URL."""
        from py_stremio.components.stremio.stremio_url import normalize_manifest_url

        try:
            url = addon.get_url(None)
        except TypeError:
            url = addon.get_url()
        return normalize_manifest_url(url)


# Re-use the same threading.Lock from the standard library
def threading_lock() -> Any:
    from threading import Lock
    return Lock()
